### ISSUE TITLE
Dropdown：select用dropdown组件，配合validation校验组件，在数据来自于搜索ajax获取时存在校验问题

### ISSUE THREAD

**Issue by chongzhi** [thx/brix-components#120]
validation组件 校验 是基于select标签的值，在select标签启用bx-search时，并且选中搜索后的结果，触发validation校验有问题，看了下文档结构，select标签的option数据没有更新，导致校验 出错

**Comment by nuysoft** [comment]
Brix 组件更新 <select> 的内容可能会 Vue 冲突，所以在获取到搜索结果后，请使用 Vue 更新 <select> 的内容。

如果发现新的方案或问题，再重新打开这个 issue。
